services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'   
      - '443:443' 
      - '81:81'   # Interface Web
#    dns:
#      - 1.1.1.1  
#      - 8.8.8.8  
    volumes:
      - /var/npm/data:/data
      - /var/npm/letsencrypt:/etc/letsencrypt
      - /var/npm/logs:/data/logs
    environment:
      - DISABLE_IPV6=true  
    networks:
      npm_network:
        ipv4_address: 172.19.0.2

networks:
  npm_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
  app-net:
    external: true
